name: libertaspeople
description: Human rights surveying app

publish_to: "none"
version: 0.2.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  device_info: ^2.0.0
  firebase_core: ^1.0.2
  firebase_messaging: ^9.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_secure_storage: ^4.1.0
  flutter_svg: ^0.21.0-nullsafety.0
  http: ^0.13.1
  intl: ^0.17.0
  json_annotation: ^4.0.1
  path_provider: ^2.0.1
  percent_indicator: ^3.0.1
  provider: ^5.0.0
  step_progress_indicator: ^0.2.5+8
  uuid: ^3.0.3

dev_dependencies:
  build_runner: ^1.11.0

  flutter_launcher_icons: ^0.9.0
  #flutter pub run flutter_launcher_icons:main

  flutter_test:
    sdk: flutter

  json_serializable: ^4.1.0
  lint: ^1.0.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path_android: 'assets/icons/libertasPeopleIcon.png'
  image_path_ios: 'assets/icons/libertasPeopleIcon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeueBd.ttf
        - asset: assets/fonts/HelveticaNeueHv.ttf
        - asset: assets/fonts/HelveticaNeueIt.ttf
        - asset: assets/fonts/HelveticaNeueLt.ttf
        - asset: assets/fonts/HelveticaNeueMed.ttf

flutter_intl:
  enabled: true
  main_locale: en
