name: libertaspeople
description: Human rights surveying app

publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  device_info: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1
  flutter_secure_storage: ^3.3.4
  flutter_svg: ^0.19.2+1
  http: ^0.12.2
  json_annotation: ^3.1.0
  path_provider: ^1.6.27
  percent_indicator: ^2.1.9
  provider: ^4.3.3
  step_progress_indicator: ^0.2.5+8
  uuid: 2.2.2

dev_dependencies:
  build_runner: ^1.11.0

  flutter_launcher_icons: ^0.8.1
  #flutter pub run flutter_launcher_icons:main

  flutter_test:
    sdk: flutter

  json_serializable: ^3.5.1
  lint: ^1.0.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path_android: 'assets/icons/libertasPeopleIcon.png'
  image_path_ios: 'assets/icons/libertasPeopleIcon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeueBd.ttf
        - asset: assets/fonts/HelveticaNeueHv.ttf
        - asset: assets/fonts/HelveticaNeueIt.ttf
        - asset: assets/fonts/HelveticaNeueLt.ttf
        - asset: assets/fonts/HelveticaNeueMed.ttf

flutter_intl:
  enabled: true
  main_locale: en
