name: libertaspeople
description: Human rights surveying app

publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.6.18
  uuid: 2.2.2
  http: ^0.12.2
  flutter_secure_storage: ^3.3.4
  device_info: ^0.4.2+8
  step_progress_indicator: ^0.2.4+7
  percent_indicator: ^2.1.7+4
  json_annotation: ^3.1.0
  provider: ^4.3.2+2
  flutter_svg: ^0.18.0
  flutter_bloc: ^6.0.6
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.3
  json_serializable: ^3.5.0
  strict_dart: ^2.1.0+1
  flutter_launcher_icons: ^0.7.5

#flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path_android: 'assets/icons/libertasPeopleIcon.png'
  image_path_ios: 'assets/icons/libertasPeopleIcon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeueBd.ttf
        - asset: assets/fonts/HelveticaNeueHv.ttf
        - asset: assets/fonts/HelveticaNeueIt.ttf
        - asset: assets/fonts/HelveticaNeueLt.ttf
        - asset: assets/fonts/HelveticaNeueMed.ttf

flutter_intl:
  enabled: true
  main_locale: en
